apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: wardviaene/k8s-demo
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: credvolume
      mountPath: /etc/creds
      readOnly: true
    volumes:
    - name: credvolume
      secret:
        secretName: db-secrets


# The secrets will be stored in:
# /etc/creds/db-secrets/username
# /etc/creds/db-secrets/password
