apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  password: cm9vdA==
  username: cGFzc3dvcmQ=
  
# echo -n "pw" | base64
# cm9vdA==
# echo -n "user" | base64
# cGFzc3dvcmQ=
# kubectl create -f secrets-db-secret.yml
# This command creates the secret
